# import utils

# def get_coherence_responses(candidate_sections, task_section):
#         coherence_responses = []
        
#         for current_section in candidate_sections:
#             coherent_prompt = f"""
#             Given the following two sections, determine if current section is coherent with the original task section.

#             My current section is:
#             "{current_section}"

#             The original task section is:
#             {task_section}

#             Answer with only the word 'True' or 'False'.
#             """
#             coherent_prompt = '\n'.join([line.lstrip() for line in coherent_prompt.split('\n')])
            
#             res = utils.chatgpt(coherent_prompt, 0.7, n=1)
#             # Make the response check more robust
#             coherence_responses.append(res[0])
        
#         # return candidate_sections with true responses
#         return [candidate_sections[i] for i, res in enumerate(coherence_responses) if res == 'True']


# candidates = [
#       "plus",
#       "Using the reviews provided, determine whether the paper should be classified as 'Accepted' or 'Rejected' for an academic conference. Please take into account the following evaluation criteria:\n\n1. **Overall Quality:** Evaluate the paper’s overall quality by considering the soundness of the methodology, clarity of the writing, and the significance of its contributions to the discipline.\n\n2. **Strengths and Weaknesses:** Identify the key strengths and weaknesses highlighted in the reviews. Pay particular attention to any differing views among the reviewers and assess how these discrepancies might impact the final decision.\n\n3. **Experimental Validation:** Analyze the rigor and quality of the experiments conducted. Are the results compelling, and do they adequately support the authors’ assertions? Ensure that comparisons with relevant methodologies are comprehensive and clearly presented.\n\n4. **Novelty and Impact:** Assess the uniqueness of the research and its potential impact on the field. Does it offer a significant advancement or perspective in relation to previous work? Consider whether the authors have sufficiently highlighted the novelty of their approach in comparison to existing methods.\n\n5. **Concerns Raised:** Consider any major concerns raised by the reviewers, especially those related to the credibility of the research, thoroughness of the experiments, and the broader implications of the results. Reflect on the necessity of a detailed comparison with related studies and how the paper situates itself within the current literature.\n\nMake your decision by weighing the overall sentiment of the reviews against the severity of any identified weaknesses. Classify the paper as 'Accepted' if the overall quality and contributions are robust enough to surpass any weaknesses, or 'Rejected' if there are significant issues consistently highlighted in the reviews, particularly regarding novelty and comparisons with similar works.", 
#       "Using the reviews provided, assess whether the paper should be categorized as 'Accepted' or 'Rejected' for an academic conference. Please refer to the evaluation criteria outlined below, considering the nuanced sentiments conveyed by the reviewers.\n\n1. **Overall Quality Assessment:** Review the paper's overall quality based on the feedback regarding methodology, clarity, and contributions. Look for both affirmative and negative sentiments to understand the general impression.\n\n2. **Strengths and Contributions:** Highlight the primary strengths and contributions of the paper as noted by the reviewers. Focus on any distinctive features that could differentiate this work from other submissions in the domain.\n\n3. **Weaknesses and Concerns:** Pay careful attention to the weaknesses and concerns mentioned by the reviewers. Identify any critical issues that might compromise the paper's validity or impact, as well as any recurring themes noted in multiple reviews.\n\n4. **Experimental Validation and Results:** Evaluate the thoroughness and quality of the experimental validation presented. Are the results persuasive? Do they effectively support the authors' claims?\n\n5. **Novelty and Impact:** Reflect on the originality of the research and its potential influence within the field. Does the paper offer new insights or advancements that are significant compared to existing work?\n\n6. **Reviewer Consensus:** Analyze the agreement among the reviewers. Are there notable disagreements in their evaluations? What does the dominant sentiment indicate regarding the paper's likelihood of acceptance?\n\nMake your classification decision based on the overall balance of strengths versus weaknesses, keeping in mind the aggregate sentiment of the reviews. Classify the paper as 'Accepted' if the strengths and contributions significantly outweigh the weaknesses, or 'Rejected' if the concerns raised are critical and diminish the paper's feasibility.",
# "` as well as `", 
# "Utilizing the reviews provided, evaluate whether the paper should be classified as 'Accepted' or 'Rejected' for an academic conference. Take into account the evaluation criteria listed below, with special attention to the weaknesses and concerns highlighted by the reviewers, as these will play a crucial role in your classification decision.\n\n1. **Overall Quality Evaluation:** Assess the paper's overall quality based on feedback related to its methodology, clarity, and contributions. Weigh positive comments against negative ones to determine the general perception.\n\n2. **Strengths and Contributions:** Recognize the main strengths and contributions of the paper as identified by the reviewers. Emphasize any unique aspects that could set this work apart from others in the field.\n\n3. **Weaknesses and Concerns:** Focus closely on the weaknesses and concerns raised by the reviewers. Pay attention to critical issues that could compromise the paper's validity or significance, as well as common themes noted across multiple reviews.\n\n4. **Experimental Validation and Results:** Assess the depth and quality of the experimental validation provided. Are the results persuasive? Do they sufficiently back up the authors' assertions?\n\n5. **Novelty and Impact:** Consider the originality of the research and its potential impact within the field. Does the paper present new insights or advancements that are important relative to existing literature?\n\n6. **Reviewer Consensus:** Evaluate the level of agreement among the reviewers. Are there significant discrepancies in their assessments? What does the prevailing sentiment suggest about the paper's chance of acceptance?\n\nMake your classification decision primarily based on the relative balance of weaknesses and strengths. If the weaknesses and concerns considerably overshadow the strengths, classify the paper as 'Rejected.' Conversely, if the strengths and contributions significantly exceed the weaknesses, classify it as 'Accepted.' Remember that critical issues raised by reviewers should heavily influence your decision.", 
# "Using the reviews provided, determine whether the paper should be classified as 'Accepted' or 'Rejected' for an academic conference. Please take into account the following evaluation criteria:\n\n1. **Overall Quality:** Evaluate the paper’s overall quality by considering the soundness of the methodology, clarity of the writing, and the significance of its contributions to the discipline.\n\n2. **Strengths and Weaknesses:** Identify the key strengths and weaknesses highlighted in the reviews. Pay particular attention to any differing views among the reviewers and assess how these discrepancies might impact the final decision.\n\n3. **Experimental Validation:** Analyze the rigor and quality of the experiments conducted. Are the results compelling, and do they adequately support the authors’ assertions? Ensure that comparisons with relevant methodologies are comprehensive and clearly presented.\n\n4. **Novelty and Impact:** Assess the uniqueness of the research and its potential impact on the field. Does it offer a significant advancement or perspective in relation to previous work? Consider whether the authors have sufficiently highlighted the novelty of their approach in comparison to existing methods.\n\n5. **Concerns Raised:** Consider any major concerns raised by the reviewers, especially those related to the credibility of the research, thoroughness of the experiments, and the broader implications of the results. Reflect on the necessity of a detailed comparison with related studies and how the paper situates itself within the current literature.\n\nMake your decision by weighing the overall sentiment of the reviews against the severity of any identified weaknesses. Classify the paper as 'Accepted' if the overall quality and contributions are robust enough to surpass any weaknesses, or 'Rejected' if there are significant issues consistently highlighted in the reviews, particularly regarding novelty and comparisons with similar works.",]


# task_section = "Using the following reviews, decide whether the paper should be categorized as 'Accepted' or 'Rejected' for an academic conference. Please take into account the evaluation criteria outlined below:\n\n1. **Overall Quality:** Assess the paper's overall quality by examining the validity of the methodology, clarity of the presentation, and the importance of the contributions made.\n2. **Strengths and Weaknesses:** Highlight the main strengths and weaknesses mentioned in the reviews. Note any discrepancies in opinions among the reviewers and evaluate how these may affect the final decision.\n3. **Experimental Validation:** Evaluate the quality and extent of the experiments performed. Are the results compelling, and do they sufficiently support the authors' claims?\n4. **Novelty and Impact:** Examine the originality of the research and its potential influence on the field. Does it present a noteworthy advancement or insight compared to prior work?\n5. **Concerns Raised:** Be mindful of any significant issues pointed out by the reviewers, particularly those concerning the soundness of the research, experimental rigor, or the implications of the findings.\n\nMake your decision by considering the prevailing sentiment of the reviews while also taking into account the seriousness of any weaknesses identified. Classify the paper as 'Accepted' if the majority reflect strong quality and contributions that outweigh the weaknesses, or 'Rejected' if substantial concerns are noted across the reviews."


# result = get_coherence_responses(candidates, task_section)
# print(result)